run_name: nwm_cdit_l_variable_k_2

# training setup
results_dir: logs
train: True
batch_size: 2
num_workers: 12
model: CDiT-L/2
lr: 8e-5

# normalization for the action space
normalize: True
grad_clip_val: 10.0
context_size: 17
skip_frame: 14

# distance bounds for distance and action and distance predictions 
distance:
  min_dist_cat: -64
  max_dist_cat: 64

# action output params
len_traj_pred: 64

# dataset specific parameters
image_size: 128
datasets:
  1x:
    data_folder: data
    train: train_v2.0_raw # path to train folder with traj_names.txt
    test: val_v2.0_raw # path to test folder with traj_names.txt
    goals_per_obs: 2
    k_min: 0
    k_max: 30